#!/usr/bin/env python3
"""
Project Janus — Interactive Setup & Configuration Wizard
═══════════════════════════════════════════════════════════

Colorized TUI powered by Rich. Guides the user through:
  1. System requirements check (Python, pip, git, Ollama)
  2. Dependency verification with version table
  3. Ollama configuration & connectivity testing
  4. Model availability check + pull option
  5. Configuration persistence (.janus_config.json + .env)
  6. Demo page launch in default browser

Usage:
    python scripts/setup_wizard.py          # Full setup wizard
    python scripts/setup_wizard.py --check  # Quick health check + launch
    python scripts/setup_wizard.py --config # Reconfigure Ollama only
"""

import os
import sys
import json
import time
import shutil
import subprocess
import webbrowser
import platform
import argparse
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, List, Tuple, Any


# ═══════════════════════════════════════════════════════════
# Bootstrap: Ensure Rich is available before anything else
# ═══════════════════════════════════════════════════════════

def _bootstrap_rich():
    """Auto-install Rich if not present (first-run safety net)."""
    try:
        import rich  # noqa: F401
        return True
    except ImportError:
        print("\n⚙ 'rich' library required for the setup wizard.")
        print("  Installing now...\n")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "rich>=13.7.0"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
        print("  ✓ Rich installed successfully.\n")
        return True

_bootstrap_rich()

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.prompt import Prompt, Confirm, IntPrompt
from rich.text import Text
from rich.align import Align
from rich.rule import Rule
from rich.tree import Tree
from rich import box


# ═══════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = PROJECT_ROOT / ".janus_config.json"
ENV_FILE = PROJECT_ROOT / ".env"
DEMO_PAGE = PROJECT_ROOT / "docs" / "index.html"
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 11434
DEFAULT_MODEL = "mistral:latest"
VERSION = "0.2.0"

console = Console()


# ═══════════════════════════════════════════════════════════
# Core Packages to Verify
# ═══════════════════════════════════════════════════════════

CORE_PACKAGES: List[Tuple[str, str]] = [
    ("requests", "requests"),
    ("httpx", "httpx"),
    ("rich", "rich"),
    ("click", "click"),
    ("beautifulsoup4", "bs4"),
    ("aiohttp", "aiohttp"),
    ("aiosqlite", "aiosqlite"),
    ("python-dotenv", "dotenv"),
    ("psutil", "psutil"),
    ("cryptography", "cryptography"),
    ("pydantic", "pydantic"),
    ("markdownify", "markdownify"),
    ("pytest", "pytest"),
    ("ruff", "ruff"),
]


# ═══════════════════════════════════════════════════════════
# Configuration Management
# ═══════════════════════════════════════════════════════════

def load_config() -> Dict[str, Any]:
    """Load saved configuration or return defaults."""
    defaults: Dict[str, Any] = {
        "ollama_host": DEFAULT_HOST,
        "ollama_port": DEFAULT_PORT,
        "ollama_url": f"http://{DEFAULT_HOST}:{DEFAULT_PORT}",
        "model": DEFAULT_MODEL,
        "auto_start_ollama": False,
        "setup_complete": False,
        "version": VERSION,
        "created": None,
        "last_run": None,
    }
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, encoding="utf-8") as f:
                saved = json.load(f)
            defaults.update(saved)
        except (json.JSONDecodeError, IOError):
            pass
    return defaults


def save_config(config: Dict[str, Any]) -> None:
    """Persist configuration to .janus_config.json and .env."""
    config["last_run"] = datetime.now().isoformat()
    if not config.get("created"):
        config["created"] = datetime.now().isoformat()
    config["version"] = VERSION

    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    # Write .env for compatibility with scripts and CI
    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("# Project Janus — Generated by Setup Wizard\n")
        f.write(f"# {datetime.now().isoformat()}\n\n")
        f.write(f"OLLAMA_HOST={config['ollama_url']}\n")
        f.write(f"JANUS_MODEL={config['model']}\n")
        f.write(f"JANUS_VERSION={VERSION}\n")
        f.write(f"JANUS_AUTO_START={str(config.get('auto_start_ollama', False)).lower()}\n")


# ═══════════════════════════════════════════════════════════
# Banner
# ═══════════════════════════════════════════════════════════

def show_banner(minimal: bool = False) -> None:
    """Display the Project Janus ASCII banner."""
    if minimal:
        console.print()
        console.print(Rule("[bold cyan]🏛️ Project Janus[/]", style="bright_blue"))
        console.print(Align.center(f"[dim]v{VERSION} — Quick Launch[/]"))
        console.print()
        return

    banner_lines = [
        "",
        "  ╔═══════════════════════════════════════════════════╗",
        "  ║                                                   ║",
        "  ║    🏛️  P R O J E C T   J A N U S               ║",
        "  ║    ═══════════════════════════════════════════     ║",
        "  ║    Sovereign Archival Intelligence                 ║",
        "  ║    Fully Local  •  No External APIs  •  No Limits ║",
        "  ║                                                   ║",
        "  ╚═══════════════════════════════════════════════════╝",
        "",
    ]
    banner_text = Text()
    for line in banner_lines:
        banner_text.append(line + "\n", style="bold magenta")

    console.print(Panel(
        Align.center(banner_text),
        title=f"[bold cyan]Setup & Configuration Wizard[/]",
        subtitle=f"[dim]v{VERSION}[/]",
        border_style="bright_blue",
        padding=(0, 2),
    ))
    console.print()


# ═══════════════════════════════════════════════════════════
# Phase 1: System Requirements
# ═══════════════════════════════════════════════════════════

def phase_system_check() -> Dict[str, Any]:
    """Verify system requirements."""
    console.print(Rule("[bold yellow]Phase 1 — System Requirements[/]"))
    console.print()

    table = Table(
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
        title="System Check",
    )
    table.add_column("Component", style="white", width=22)
    table.add_column("Status", justify="center", width=12)
    table.add_column("Details", style="dim")

    info: Dict[str, Any] = {}

    # Python version
    py_ver = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    py_ok = sys.version_info >= (3, 10)
    info["python"] = py_ok
    table.add_row(
        "Python",
        "[green]✓ PASS[/]" if py_ok else "[red]✗ FAIL[/]",
        f"v{py_ver}" + ("" if py_ok else " — 3.10+ required"),
    )

    # pip
    pip_ok = False
    pip_ver = "N/A"
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "--version"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            pip_ver = result.stdout.split()[1]
            pip_ok = True
    except Exception:
        pass
    info["pip"] = pip_ok
    table.add_row(
        "pip",
        "[green]✓ PASS[/]" if pip_ok else "[red]✗ FAIL[/]",
        f"v{pip_ver}" if pip_ok else "pip not available",
    )

    # git
    git_ok = False
    git_ver = "N/A"
    try:
        result = subprocess.run(
            ["git", "--version"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            git_ver = result.stdout.strip().replace("git version ", "")
            git_ok = True
    except Exception:
        pass
    info["git"] = git_ok
    table.add_row(
        "Git",
        "[green]✓ PASS[/]" if git_ok else "[yellow]⚠ WARN[/]",
        f"v{git_ver}" if git_ok else "Optional — recommended for updates",
    )

    # OS info
    os_info = f"{platform.system()} {platform.release()}"
    table.add_row("Operating System", "[blue]✓ INFO[/]", os_info)
    table.add_row("Architecture", "[blue]✓ INFO[/]", platform.machine())

    # Ollama in PATH
    ollama_path = shutil.which("ollama")
    info["ollama_in_path"] = bool(ollama_path)
    table.add_row(
        "Ollama in PATH",
        "[green]✓ FOUND[/]" if ollama_path else "[yellow]⚠ WARN[/]",
        str(ollama_path) if ollama_path else "Not found — install from ollama.com",
    )

    # Demo page exists
    demo_exists = DEMO_PAGE.exists()
    info["demo_page"] = demo_exists
    table.add_row(
        "Demo Page",
        "[green]✓ FOUND[/]" if demo_exists else "[red]✗ MISSING[/]",
        str(DEMO_PAGE.relative_to(PROJECT_ROOT)) if demo_exists else "docs/index.html not found",
    )

    console.print(table)
    console.print()

    if not py_ok:
        console.print("[bold red]✗ Python 3.10+ is required. Please upgrade and try again.[/]")
        sys.exit(1)

    return info


# ═══════════════════════════════════════════════════════════
# Phase 2: Dependency Verification
# ═══════════════════════════════════════════════════════════

def phase_dependency_check() -> bool:
    """Verify core package installation."""
    console.print(Rule("[bold yellow]Phase 2 — Dependency Verification[/]"))
    console.print()

    table = Table(
        box=box.ROUNDED,
        show_header=True,
        header_style="bold cyan",
        title="Core Packages",
    )
    table.add_column("Package", style="white", width=20)
    table.add_column("Status", justify="center", width=12)
    table.add_column("Version", style="dim")

    missing: List[str] = []

    for pkg_name, import_name in CORE_PACKAGES:
        try:
            mod = __import__(import_name)
            version = getattr(mod, "__version__", getattr(mod, "VERSION", "installed"))
            table.add_row(pkg_name, "[green]✓ OK[/]", str(version))
        except ImportError:
            table.add_row(pkg_name, "[red]✗ MISSING[/]", "—")
            missing.append(pkg_name)

    console.print(table)
    console.print()

    if missing:
        console.print(
            f"[yellow]⚠ {len(missing)} package(s) missing:[/] "
            f"[dim]{', '.join(missing)}[/]"
        )
        console.print()
        if Confirm.ask(
            "[cyan]Install missing packages from requirements.txt?[/]",
            default=True,
        ):
            req_file = PROJECT_ROOT / "requirements.txt"
            if req_file.exists():
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                ) as progress:
                    task = progress.add_task("Installing dependencies...", total=None)
                    result = subprocess.run(
                        [sys.executable, "-m", "pip", "install", "-r", str(req_file)],
                        capture_output=True, text=True,
                    )
                    if result.returncode == 0:
                        progress.update(
                            task, description="[green]✓ Dependencies installed![/]"
                        )
                    else:
                        progress.update(
                            task,
                            description="[yellow]⚠ Some packages may have failed[/]",
                        )
                console.print()
            else:
                console.print("[red]✗ requirements.txt not found![/]")
        console.print()
    else:
        console.print("[green]✓ All core dependencies verified.[/]\n")

    return len(missing) == 0


# ═══════════════════════════════════════════════════════════
# Phase 3: Ollama Configuration
# ═══════════════════════════════════════════════════════════

def _check_ollama(host: str, port: int, timeout: int = 5) -> Tuple[bool, List[str]]:
    """Test connectivity to Ollama. Returns (ok, model_names)."""
    try:
        import requests
        url = f"http://{host}:{port}/api/tags"
        resp = requests.get(url, timeout=timeout)
        if resp.status_code == 200:
            data = resp.json()
            models = [m.get("name", "?") for m in data.get("models", [])]
            return True, models
    except Exception:
        pass
    return False, []


def _start_ollama(host: str, port: int) -> bool:
    """Attempt to start Ollama server as a background process."""
    console.print(f"[yellow]⚡ Starting Ollama on {host}:{port}...[/]")

    ollama_path = shutil.which("ollama")
    if not ollama_path:
        console.print("[red]✗ Cannot find 'ollama' in PATH.[/]")
        console.print("[dim]  Install from: https://ollama.com/download[/]\n")
        return False

    try:
        env = os.environ.copy()
        env["OLLAMA_HOST"] = f"{host}:{port}"

        if platform.system() == "Windows":
            # Windows: detached background process
            subprocess.Popen(
                ["ollama", "serve"],
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                creationflags=subprocess.CREATE_NO_WINDOW | subprocess.DETACHED_PROCESS,
            )
        else:
            # Unix: new session
            subprocess.Popen(
                ["ollama", "serve"],
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )

        # Poll until Ollama is ready (up to 30 seconds)
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            task = progress.add_task("Waiting for Ollama...", total=None)
            for i in range(30):
                time.sleep(1)
                ok, _ = _check_ollama(host, port, timeout=2)
                if ok:
                    progress.update(task, description="[green]✓ Ollama is running![/]")
                    time.sleep(0.5)
                    console.print()
                    return True
                progress.update(
                    task, description=f"Waiting for Ollama... ({i + 1}s)"
                )

        console.print("[red]✗ Ollama did not start within 30 seconds.[/]\n")
        return False

    except Exception as e:
        console.print(f"[red]✗ Failed to start Ollama: {e}[/]\n")
        return False


def phase_ollama_config(config: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]:
    """Interactive Ollama configuration with connectivity testing."""
    console.print(Rule("[bold yellow]Phase 3 — Ollama Configuration[/]"))
    console.print()

    host = config.get("ollama_host", DEFAULT_HOST)
    port = config.get("ollama_port", DEFAULT_PORT)

    # Test current/saved connection
    console.print(f"[cyan]Testing Ollama at {host}:{port}...[/]")
    ok, models = _check_ollama(host, port)

    if ok:
        console.print(f"[green]✓ Ollama is running![/]  [{len(models)} model(s)]")
        if models:
            for m in models[:10]:
                console.print(f"  [dim]• {m}[/]")
        console.print()
        config["ollama_host"] = host
        config["ollama_port"] = port
        config["ollama_url"] = f"http://{host}:{port}"
        return config, True

    # Not available — show options
    console.print()
    console.print(Panel(
        "[bold yellow]⚠ Ollama is not responding[/]\n\n"
        f"  Tried: [cyan]http://{host}:{port}[/]\n\n"
        "  Ollama provides the local AI brain for Project Janus.\n"
        "  Install from: [link=https://ollama.com/download]https://ollama.com/download[/]",
        title="[yellow]Connection Failed[/]",
        border_style="yellow",
    ))
    console.print()

    console.print("[bold]Options:[/]")
    console.print(f"  [cyan]1[/] — Start Ollama now (port {port})")
    console.print("  [cyan]2[/] — Configure a different host/port")
    console.print("  [cyan]3[/] — Skip (continue without Ollama)")
    console.print()

    choice = Prompt.ask(
        "[cyan]Select option[/]",
        choices=["1", "2", "3"],
        default="1",
    )

    if choice == "1":
        started = _start_ollama(host, port)
        config["auto_start_ollama"] = started
        config["ollama_host"] = host
        config["ollama_port"] = port
        config["ollama_url"] = f"http://{host}:{port}"
        return config, started

    elif choice == "2":
        new_host = Prompt.ask("[cyan]Ollama host[/]", default=host)
        new_port = IntPrompt.ask("[cyan]Ollama port[/]", default=port)
        console.print(f"\n[cyan]Testing {new_host}:{new_port}...[/]")
        ok, models = _check_ollama(new_host, new_port)
        if ok:
            console.print(f"[green]✓ Connected! {len(models)} model(s) available.[/]\n")
        else:
            console.print("[yellow]⚠ Still not reachable. Config saved — you can start Ollama later.[/]\n")
        config["ollama_host"] = new_host
        config["ollama_port"] = new_port
        config["ollama_url"] = f"http://{new_host}:{new_port}"
        return config, ok

    else:
        console.print("[yellow]⚠ Skipping — demo will run in offline mode.[/]\n")
        config["ollama_host"] = host
        config["ollama_port"] = port
        config["ollama_url"] = f"http://{host}:{port}"
        return config, False


# ═══════════════════════════════════════════════════════════
# Phase 4: Model Verification
# ═══════════════════════════════════════════════════════════

def phase_model_check(config: Dict[str, Any], ollama_ok: bool) -> Dict[str, Any]:
    """Verify the configured model is available; offer to pull if not."""
    console.print(Rule("[bold yellow]Phase 4 — Model Verification[/]"))
    console.print()

    if not ollama_ok:
        console.print("[yellow]⚠ Ollama not available — skipping model check.[/]\n")
        return config

    model = config.get("model", DEFAULT_MODEL)
    host = config["ollama_host"]
    port = config["ollama_port"]

    ok, models = _check_ollama(host, port)
    target_base = model.split(":")[0]

    if any(target_base in m for m in models):
        console.print(f"[green]✓ Model '{model}' is available.[/]\n")
        return config

    console.print(f"[yellow]⚠ Model '{model}' not found locally.[/]")
    if models:
        console.print(f"[dim]  Available models: {', '.join(models[:8])}[/]")
    console.print()

    if Confirm.ask(
        f"[cyan]Pull '{model}' now?[/] [dim](may take several minutes)[/]",
        default=True,
    ):
        try:
            console.print(f"[cyan]Pulling {model}...[/]")
            result = subprocess.run(
                ["ollama", "pull", model],
                timeout=600,
            )
            if result.returncode == 0:
                console.print(f"[green]✓ {model} ready.[/]\n")
            else:
                console.print(f"[red]✗ Pull exited with code {result.returncode}.[/]\n")
        except subprocess.TimeoutExpired:
            console.print("[red]✗ Pull timed out after 10 minutes.[/]\n")
        except Exception as e:
            console.print(f"[red]✗ Pull failed: {e}[/]\n")
    else:
        alt = Prompt.ask(
            "[cyan]Use a different model instead? (leave blank to keep current)[/]",
            default="",
        )
        if alt.strip():
            config["model"] = alt.strip()
            console.print(f"[green]✓ Model set to '{alt.strip()}'.[/]\n")

    return config


# ═══════════════════════════════════════════════════════════
# Phase 5: Summary & Save
# ═══════════════════════════════════════════════════════════

def phase_summary_and_save(
    config: Dict[str, Any],
    system_info: Dict[str, Any],
    ollama_ok: bool,
) -> Dict[str, Any]:
    """Display final summary tree and persist configuration."""
    console.print(Rule("[bold yellow]Phase 5 — Configuration Summary[/]"))
    console.print()

    tree = Tree("[bold cyan]🏛️ Project Janus[/]")

    # System
    sys_branch = tree.add("[bold white]System[/]")
    py_ver = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    sys_branch.add(f"Python {py_ver}")
    sys_branch.add(f"{platform.system()} {platform.release()} ({platform.machine()})")

    # Ollama
    ollama_branch = tree.add("[bold white]Ollama[/]")
    ollama_branch.add(f"URL: [cyan]{config['ollama_url']}[/]")
    ollama_branch.add(f"Model: [cyan]{config['model']}[/]")
    status = "[green]✓ Connected[/]" if ollama_ok else "[yellow]⚠ Offline[/]"
    ollama_branch.add(f"Status: {status}")
    auto = "[green]Yes[/]" if config.get("auto_start_ollama") else "[dim]No[/]"
    ollama_branch.add(f"Auto-start: {auto}")

    # Files
    files_branch = tree.add("[bold white]Files[/]")
    files_branch.add(f"Config:  [dim]{CONFIG_FILE.relative_to(PROJECT_ROOT)}[/]")
    files_branch.add(f"Env:     [dim]{ENV_FILE.relative_to(PROJECT_ROOT)}[/]")
    files_branch.add(f"Demo:    [dim]{DEMO_PAGE.relative_to(PROJECT_ROOT)}[/]")

    console.print(tree)
    console.print()

    # Save
    config["setup_complete"] = True
    save_config(config)
    console.print("[green]✓ Configuration saved.[/]\n")

    return config


# ═══════════════════════════════════════════════════════════
# Phase 6: Launch Demo
# ═══════════════════════════════════════════════════════════

def phase_launch_demo(config: Dict[str, Any], ollama_ok: bool) -> None:
    """Open the demo page in the default browser."""
    console.print(Rule("[bold yellow]Phase 6 — Launch Demo[/]"))
    console.print()

    if not DEMO_PAGE.exists():
        console.print("[red]✗ Demo page not found at docs/index.html[/]")
        console.print("[dim]  Make sure you're running from the project root.[/]\n")
        return

    if not ollama_ok:
        console.print(Panel(
            "[yellow]⚠ Ollama is not running.[/]\n\n"
            "  The demo page will load, but AI queries will fail\n"
            "  until Ollama is started.\n\n"
            "  Start manually: [cyan]ollama serve[/]",
            title="[yellow]Limited Mode[/]",
            border_style="yellow",
        ))
        console.print()

    if Confirm.ask("[cyan]Open demo page in browser?[/]", default=True):
        demo_url = DEMO_PAGE.as_uri()
        webbrowser.open(demo_url)
        console.print(f"[green]✓ Demo page opened![/]\n")
    else:
        console.print(f"[dim]  Demo available at: {DEMO_PAGE}[/]\n")

    # Final success panel
    console.print(Panel(
        Align.center(Text.from_markup(
            "[bold green]✓ Setup Complete![/]\n\n"
            f"[white]Config:[/]      [cyan]{CONFIG_FILE.relative_to(PROJECT_ROOT)}[/]\n"
            f"[white]Environment:[/] [cyan]{ENV_FILE.relative_to(PROJECT_ROOT)}[/]\n"
            f"[white]Demo Page:[/]   [cyan]{DEMO_PAGE.relative_to(PROJECT_ROOT)}[/]\n\n"
            "[dim]─── Quick Commands ───[/]\n"
            "[dim]Run again:[/]     [cyan]run.bat[/] or [cyan]./run.sh[/]\n"
            "[dim]Reconfigure:[/]   [cyan]python scripts/setup_wizard.py --config[/]\n"
            "[dim]Health check:[/]  [cyan]python scripts/setup_wizard.py --check[/]"
        )),
        title="[bold green]🏛️ Project Janus Ready[/]",
        border_style="green",
        padding=(1, 3),
    ))
    console.print()


# ═══════════════════════════════════════════════════════════
# Quick Check Mode (for run.bat / run.sh)
# ═══════════════════════════════════════════════════════════

def quick_check(config: Dict[str, Any]) -> bool:
    """
    Quick Ollama health check used by run.bat/run.sh.
    Notifies user if Ollama is unavailable and offers to start it.
    """
    host = config.get("ollama_host", DEFAULT_HOST)
    port = config.get("ollama_port", DEFAULT_PORT)

    console.print(f"[cyan]Checking Ollama at {host}:{port}...[/]")
    ok, models = _check_ollama(host, port)

    if ok:
        console.print(
            f"[green]✓ Ollama running[/] — "
            f"{len(models)} model(s) available"
        )
        if models:
            console.print(f"  [dim]{', '.join(models[:5])}[/]")
        console.print()
        return True

    # Not available — warn and offer options
    console.print()
    console.print(Panel(
        f"[bold yellow]⚠ Ollama is not responding[/]\n\n"
        f"  Configured host: [cyan]http://{host}:{port}[/]\n\n"
        "  The AI brain requires a running Ollama server.\n"
        f"  Default port: [cyan]{DEFAULT_PORT}[/]",
        title="[yellow]Ollama Unavailable[/]",
        border_style="yellow",
    ))
    console.print()

    console.print("[bold]Options:[/]")
    console.print(f"  [cyan]1[/] — Start Ollama (port {port})")
    console.print("  [cyan]2[/] — Continue without Ollama (limited mode)")
    console.print("  [cyan]3[/] — Exit")
    console.print()

    choice = Prompt.ask("[cyan]Select[/]", choices=["1", "2", "3"], default="1")

    if choice == "1":
        started = _start_ollama(host, port)
        if started:
            config["auto_start_ollama"] = True
            save_config(config)
        return started
    elif choice == "3":
        console.print("[dim]Exiting.[/]")
        sys.exit(0)

    console.print("[yellow]⚠ Continuing in limited mode.[/]\n")
    return False


# ═══════════════════════════════════════════════════════════
# Main Entry Point
# ═══════════════════════════════════════════════════════════

def main() -> None:
    """CLI entry point — routes to full wizard, quick check, or reconfig."""
    parser = argparse.ArgumentParser(
        description="Project Janus — Setup & Configuration Wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/setup_wizard.py          # Full setup\n"
            "  python scripts/setup_wizard.py --check  # Quick health check\n"
            "  python scripts/setup_wizard.py --config # Reconfigure Ollama\n"
        ),
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Quick health check and launch (skip full setup)",
    )
    parser.add_argument(
        "--config", action="store_true",
        help="Reconfigure Ollama settings only",
    )
    args = parser.parse_args()

    config = load_config()

    # ── Quick Check Mode ──────────────────────────────────
    if args.check:
        show_banner(minimal=True)
        ollama_ok = quick_check(config)
        config["last_run"] = datetime.now().isoformat()
        save_config(config)
        phase_launch_demo(config, ollama_ok)
        return

    # ── Reconfig Mode ─────────────────────────────────────
    if args.config:
        show_banner(minimal=True)
        config, ollama_ok = phase_ollama_config(config)
        if ollama_ok:
            config = phase_model_check(config, ollama_ok)
        save_config(config)
        console.print("[green]✓ Configuration updated.[/]\n")
        return

    # ── Full Setup Wizard ─────────────────────────────────
    show_banner()

    console.print(
        "[dim]This wizard will configure your Project Janus installation.\n"
        "It checks system requirements, verifies dependencies, configures\n"
        "Ollama for local AI inference, and launches the demo page.[/]\n"
    )

    if not Confirm.ask("[cyan]Ready to begin?[/]", default=True):
        console.print("[dim]Setup cancelled. Run again anytime.[/]")
        return

    console.print()

    # Phase 1: System
    system_info = phase_system_check()

    # Phase 2: Dependencies
    phase_dependency_check()

    # Phase 3: Ollama
    config, ollama_ok = phase_ollama_config(config)

    # Phase 4: Model
    config = phase_model_check(config, ollama_ok)

    # Phase 5: Summary
    config = phase_summary_and_save(config, system_info, ollama_ok)

    # Phase 6: Launch
    phase_launch_demo(config, ollama_ok)


if __name__ == "__main__":
    main()
